import './globals.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import '../../node_modules/@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import Nav from './components/Nav'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Nav />
        </header>
        <main>
          {children}
          </main>
        </body>
    </html>
  )
}
